services:

  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html:z
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: party        # el nombre que usás en party.sql
      MYSQL_USER: usuario
      MYSQL_PASSWORD: pariesJAJA
    volumes:
      - ./code/party.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root